import express from 'express';
import auth, { requireFullAccess } from '../middleware/auth.js';
import { validateSupplier } from '../middleware/validate.js';
import { getAll, create, update, remove } from '../controllers/supplierController.js';
import asyncHandler from '../middleware/asyncHandler.js';
const router = express.Router();
router.get('/', auth, asyncHandler(getAll));
router.post('/', auth, requireFullAccess, validateSupplier, create);
router.put('/:id', auth, requireFullAccess, validateSupplier, update);
router.delete('/:id', auth, requireFullAccess, asyncHandler(remove));
export default router;
