import { useEffect, useMemo, useState } from 'react';
import toast from 'react-hot-toast';
import { Plus, Save, Trash2 } from 'lucide-react';
import api from '../api/axios';
import { formatCurrency } from '../utils/format';

const emptyItem = { product_id: '', quantity: 1, import_price: 0 };

export default function PurchaseOrders() {
  const [orders, setOrders] = useState([]); const [suppliers, setSuppliers] = useState([]); const [products, setProducts] = useState([]);
  const [supplierId, setSupplierId] = useState(''); const [items, setItems] = useState([{ ...emptyItem }]); const [note, setNote] = useState(''); const [saving, setSaving] = useState(false);
  const load = async () => { const [a,b,c] = await Promise.all([api.get('/purchase-orders'),api.get('/suppliers'),api.get('/products')]); setOrders(a.data); setSuppliers(b.data.filter((x)=>x.status==='active')); setProducts(c.data); };
  useEffect(() => { load().catch(() => toast.error('Không thể tải dữ liệu nhập hàng')); }, []);
  const total = useMemo(() => items.reduce((sum,x)=>sum+Number(x.quantity||0)*Number(x.import_price||0),0),[items]);
  const updateItem=(index,field,value)=>setItems((rows)=>rows.map((x,i)=>i===index?{...x,[field]:value}:x));
  const submit=async(event)=>{event.preventDefault();setSaving(true);try{await api.post('/purchase-orders',{supplier_id:Number(supplierId),note,items:items.map((x)=>({...x,product_id:Number(x.product_id),quantity:Number(x.quantity),import_price:Number(x.import_price)}))});toast.success('Đã tạo phiếu nhập và cập nhật tồn kho');setItems([{...emptyItem}]);setNote('');await load();}catch(error){toast.error(error.response?.data?.message||'Không thể tạo phiếu nhập');}finally{setSaving(false);}};
  return <div className="space-y-6"><header><h1 className="text-2xl font-extrabold text-gray-950">Phiếu nhập hàng</h1><p className="mt-1 text-sm text-gray-500">Nhập hàng và cập nhật tồn kho trong cùng một giao dịch.</p></header>
    <form onSubmit={submit} className="space-y-4 border-y border-gray-200 bg-white py-5"><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-semibold">Nhà cung cấp<select required value={supplierId} onChange={(e)=>setSupplierId(e.target.value)} className="mt-1 h-10 w-full rounded border px-3"><option value="">Chọn nhà cung cấp</option>{suppliers.map((s)=><option key={s.id} value={s.id}>{s.name||s.supplier_name}</option>)}</select></label><label className="text-sm font-semibold">Ghi chú<input value={note} onChange={(e)=>setNote(e.target.value)} className="mt-1 h-10 w-full rounded border px-3"/></label></div>
    <div className="space-y-2">{items.map((x,index)=><div key={index} className="grid gap-2 md:grid-cols-[1fr_120px_160px_40px]"><select required value={x.product_id} onChange={(e)=>updateItem(index,'product_id',e.target.value)} className="h-10 rounded border px-3"><option value="">Chọn sản phẩm</option>{products.map((p)=><option key={p.id} value={p.id}>{p.name}</option>)}</select><input required min="1" type="number" value={x.quantity} onChange={(e)=>updateItem(index,'quantity',e.target.value)} className="h-10 rounded border px-3" title="Số lượng"/><input required min="0" type="number" value={x.import_price} onChange={(e)=>updateItem(index,'import_price',e.target.value)} className="h-10 rounded border px-3" title="Giá nhập"/><button type="button" title="Xóa dòng" onClick={()=>setItems((rows)=>rows.length===1?rows:rows.filter((_,i)=>i!==index))} className="grid h-10 place-items-center text-red-600"><Trash2 size={18}/></button></div>)}</div>
    <div className="flex flex-wrap items-center justify-between gap-3"><button type="button" onClick={()=>setItems((rows)=>[...rows,{...emptyItem}])} className="inline-flex items-center gap-2 rounded border px-4 py-2 font-semibold"><Plus size={17}/>Thêm sản phẩm</button><div className="flex items-center gap-4"><strong>{formatCurrency(total)}</strong><button disabled={saving} className="inline-flex items-center gap-2 rounded bg-brand px-5 py-2 font-bold text-white disabled:opacity-50"><Save size={17}/>{saving?'Đang lưu':'Tạo phiếu nhập'}</button></div></div></form>
    <div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-b"><tr><th className="p-3">Mã phiếu</th><th>Nhà cung cấp</th><th>Người tạo</th><th>Tổng tiền</th><th>Ngày tạo</th></tr></thead><tbody>{orders.map((o)=><tr key={o.id} className="border-b"><td className="p-3 font-bold">{o.purchase_code}</td><td>{o.supplier_name}</td><td>{o.created_by_name}</td><td>{formatCurrency(o.total_amount)}</td><td>{new Date(o.created_at).toLocaleString('vi-VN')}</td></tr>)}</tbody></table></div></div>;
}
